name: Sync with Paratranz

on:
  workflow_dispatch:
  schedule:
    - cron: 20 16 * * *

jobs:
  sync:
    name: sync
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull from Paratranz
        run: 'wget -O latest.zip --header="Authorization: 78a7edf21e3b6d9084e2e0cb66f67f55" https://paratranz.cn/api/projects/3318/artifacts/download'
      - name: Setup Python
        run: |
          python -m pip install --upgrade pip
      - name: Update
        run: |
          rm -rf paratranz
          unzip latest.zip "utf8/*"
          mv utf8 paratranz
          cd paratranz
          mv St200 ..
          mv St300 ..

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '"paratranz"'
          default_author: github_actions
          message: 'Sync with Paratranz'
          push: true
