name: Sync with Paratranz

on:
  workflow_dispatch:
  schedule:
    - cron: 20 16 * * *

jobs:
  sync:
    name: sync
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull from Paratranz
        run: 'wget -O latest.zip --header="Authorization: b2a8dfb6083206a67c55dff92683866e" https://paratranz.cn/api/projects/3318/artifacts/download'
      - name: Setup Python
        run: |
          python -m pip install --upgrade pip
      - name: Update
        run: |
          rm -rf paratranz
          unzip latest.zip "utf8/*"
          mv utf8 paratranz
          cd paratranz
          mv St200 ../
          mv St300 ../ 
      - name: Sort & Reconvert
        run: python reconvert.py
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '"paratranz" "csv"'
          default_author: github_actions
          message: 'Sync with Paratranz'
          push: true
